### ISSUE TITLE
[cross-platform] [verbosity] Use argv[0] instead of "php.exe" (C/Unix behaviour)

### ISSUE THREAD

**Issue by chl0e3e** [gizmore/phpgdo#2]
[Code](https://github.com/gizmore/phpgdo/blob/main/gdo_adm.php#L70)

Usage should derive the command's executable name from the operating system

https://stackoverflow.com/questions/7941536/windows-vs-linux-gcc-argv0-value

**Comment by gizmore** [comment]
Thank you.
This issue got resolved meanwhile on a coding spree someday.
